image:
- Ubuntu1804

clone_depth: 25

build: off

init:
- sh: sudo apt install -yq --no-install-recommends liblapacke-dev

install:
- sh: cmake -B build
- cmake --build build --parallel

test_script:
- cd build
- ctest --parallel --output-on-failure

