image:
- Ubuntu1804

clone_depth: 25

build: off

init:
- sh: sudo apt install -yq --no-install-recommends liblapacke-dev

install:
- cd build

- sh: cmake ..

- cmake --build .

test_script:
# now build the test
- cmake --build .
- ctest --output-on-failure

