# gfortran >= 6 required for fortran2008
language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

python: 3.6

env: FC=gfortran-6

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
    - gfortran-6
    - liblapack-dev

matrix:
  include:
  - os: linux
#  - os: osx
#    before_install: brew install gcc > /dev/null

before_install:
- pip install cmakeutils
- cmake_setup 3.14.1
- export PATH=$HOME/.local/cmake-3.14.1-Linux-x86_64/bin:$PATH

install:
- cd build
- cmake ..
- cmake --build . -j

script:
- cd $TRAVIS_BUILD_DIR/tests/build
- cmake ..
- cmake --build .
- ctest --output-on-failure

