# gfortran >= 6 required for fortran2008
language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

env: FC=gfortran-6

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
    - gfortran-6
    - liblapack-dev

matrix:
  include:
  - os: linux
#  - os: osx
#    before_install: brew install gcc > /dev/null

before_install:
- python -m pip install meson
- curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip -o ninja-linux.zip
- sudo unzip ninja-linux.zip -d /usr/local/bin/

install: meson build

script: meson test -C build
