# gfortran >= 6 required for fortran2008
language: c
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

env: FC=gfortran-6

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
    - gfortran-6
    - liblapack-dev

matrix:
  include:
  - os: linux
#  - os: osx
#    before_install: brew install gcc > /dev/null


install:
- cmake -B build
- cmake --build . -j

script:
- cd $TRAVIS_BUILD_DIR/tests/build
- cmake ..
- cmake --build .
- ctest --output-on-failure

