# gfortran >= 6 required for fortran2008
language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

env: FC=gfortran-6

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
    - gfortran-6

matrix:
  include:
  - os: linux
    name: "Own Lapack"
  - os : linux
    name: "system lapack"
    before_install: sudo apt install --no-install-recommends -yq liblapack-dev


install:
- python -m pip install meson
- curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip -o ninja-linux.zip
- sudo unzip ninja-linux.zip -d /usr/local/bin/

before_script: meson build

script: meson test -C build
